//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontograma.Models.Odo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.DetalleCita = new HashSet<DetalleCita>();
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public string CitaId { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        [Display(Name = "Clínica")]
        public string ClinicaId { get; set; }
        public string PacienteId { get; set; }
        public string Estado { get; set; }

        [Display(Name = "Clínica")]
        public virtual Clinica Clinica { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCita> DetalleCita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
    }


    //CITA

    public class HistorialViewModel
    {

        [Display(Name = "Fecha")]
        public string Fecha { get; set; }

        [Display(Name = "Hora")]
        public string Hora { get; set; }

        [Display(Name = "Seleccione una clínica")]
        public string ClinicaId { get; set; }

        [Display(Name = "Estudiante")]
        public string Estudiante { get; set; }

        public Cita cita { get; set;  }
        public DetalleCita detalle { get; set; } 


    }


    public class CitaViewModel
    {
        [Required]
        [Display(Name = "Fecha")]
        public string Fecha { get; set; }
        [Required]
        [Display(Name = "Hora")]
        public string Hora { get; set; }
        [Required]
        [Display(Name = "Seleccione una clínica")]
        public string ClinicaId { get; set; }
    }

    public class CitaEditarModel
    {
        public string CitaId { get; set; }
        [Required]
        [Display(Name = "Fecha")]
        public string Fecha { get; set; }
        [Required]
        [Display(Name = "Hora")]
        public string Hora { get; set; }
        [Required]
        [Display(Name = "Seleccione una clínica")]
        public string ClinicaId { get; set; }
    }

    public class DetalleCitaModel
    {
        public string CitaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }

        public Cita cita { get; set; }
        public Paciente paciente { get; set; }
    }

    public class DetalleEstudianteModel
    {
        //Datos de estudiante
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string EscuelaId { get; set; }
        //Datos de la cita

        public DetalleCita detalle { get; set; }
        public Estudiante estudiante { get; set; }
    }

    public class VerEstudiante
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Clinica { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string EscuelaId { get; set; }

        public Cita cita { get; set; }
        public DetalleCita dCita { get; set; }
        public Estudiante estudiante { get; set; }
    }

    public class VerExpediente
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Clinica { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string EscuelaId { get; set; }
        public Diagnostico diagnostico { get; set; }
        public Cita cita { get; set; }
        public DetalleCita dCita { get; set; }
        public Estudiante estudiante { get; set; }

    }
}
