//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontograma.Models.Odo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetallePaciente
    {
        public string DetPacId { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string Cp { get; set; }
        public string DerechohabienciaId { get; set; }
        public string EstadoId { get; set; }
        public string OcupacionId { get; set; }
        public string EscolaridadId { get; set; }
        public string PacienteId { get; set; }
    
        public virtual Derechohabiencia Derechohabiencia { get; set; }
        public virtual Escolaridad Escolaridad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
        public virtual Paciente Paciente { get; set; }
    }

    public class DetalleViewModel
    {
        [Required]
        [Display(Name = "Calle")]
        public string Calle { get; set; }
        [Required]
        [Display(Name = "Colonia")]
        public string Colonia { get; set; }
        [Required]
        [Display(Name = "CP")]
        public string Cp { get; set; }
        [Required]
        [Display(Name = "Institucion de derechohabiencia")]
        public string DerechohabienciaId { get; set; }
        [Required]
        [Display(Name = "Estado de procedencia")]
        public string EstadoId { get; set; }
        [Required]
        [Display(Name = "Ocupacion")]
        public string OcupacionId { get; set; }
        [Required]
        [Display(Name = "Grado maximo de estudios")]
        public string EscolaridadId { get; set; }
    }
}
