//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontograma.Models.Odo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.DetalleCita = new HashSet<DetalleCita>();
        }
    
        public string EstudianteId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EscuelaId { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCita> DetalleCita { get; set; }
        public virtual Escuela Escuela { get; set; }
    }
    //estudiante


    public class EstudianteViewModel
    {
        [Required]
        [Display(Name = "Nombre o nombres")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Apellidos")]
        public string Apellido { get; set; }
        [Required]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "Fecha de nacimiento")]
        public string FechaNacimiento { get; set; }
        [Required]
        [Display(Name = "Sexo")]
        public string Sexo { get; set; }
        [Required]
        [Display(Name = "Escuela")]
        public string EscuelaId { get; set; }
    }

    public class ConfirmadasViewModel
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Clinica { get; set; }

        public Cita cita { get; set; }
        public DetalleCita detalle { get; set; }
    }

    public class AtendidasViewModel
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Clinica { get; set; }
        public string Paciente { get; set; }
        public Cita cita { get; set; }
        public DetalleCita detalle { get; set; }
    }
}
